# Generated by Django 2.1 on 2021-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('dowload_links', models.CharField(max_length=800)),
            ],
        ),
    ]
